export const PROJECTS = [
  // {
  //   id: 1,
  //   link: "https://terjeee.github.io/2022-08-21-bank-landing-page/",
  //   linkRepo: "https://github.com/terjeee/2022-08-21-bank-landing-page",
  //   title: "EasyBank - Landing Page",
  //   colorDot: "#F1E05A",
  //   text: "React, React Router",
  // },
  {
    id: 2,
    link: "https://terjeee.github.io/2022.05.27-Advice-Generator/",
    linkRepo: "https://github.com/terjeee/2022.05.27-Advice-Generator",
    title: "Advice Generator",
    colorDot: "#563D7C",
    text: "Javascript",
  },
  {
    id: 3,
    link: " https://terjeee.github.io/2022-08-10-calculator-app/",
    linkRepo: "https://github.com/terjeee/2022-08-10-calculator-app",
    title: "Calculator",
    colorDot: "#F1E05A",
    text: "React",
  },
  {
    id: 4,
    link: "https://svelte-test-mauve.vercel.app/",
    linkRepo: "https://github.com/terjeee/svelte-test",
    colorDot: "#FF3E00",
    title: "Svelte Test",
    text: "SvelteKit, Tailwind, Typescript",
  },
  {
    id: 5,
    link: "https://terjeee.github.io/2022-08-14-ip-address-tracker/",
    linkRepo: "https://github.com/terjeee/2022-08-14-ip-address-tracker",
    title: "IP Address Tracker",
    colorDot: "#F1E05A",
    text: "React, API",
  },
  {
    id: 6,
    link: "https://terjeee.github.io/2022-02-12-GuessNumber/",
    linkRepo: "https://github.com/terjeee/2022.02.12-GuessNumber",
    title: "Guess the Number",
    colorDot: "#F1E05A",
    text: "Javascript  (for større skjermer)",
  },
  {
    id: 7,
    link: "https://terjeee.github.io/url-shorten/",
    linkRepo: "https://github.com/terjeee/url-shorten",
    colorDot: "#41B883",
    title: "URL Shortener",
    text: "Vue, Typescript",
  },
  {
    id: 8,
    link: "https://terjeee.github.io/to-do/",
    linkRepo: "https://github.com/terjeee/to-to/",
    colorDot: "#3178c6",
    title: "To-do List",
    text: "React, Typescript, Redux, SCSS",
  },
  {
    id: 9,
    link: "https://react-sandbox-kappa.vercel.app/",
    linkRepo: "https://github.com/terjeee/react-sandbox",
    colorDot: "#3178c6",
    title: "Data Vizualisation",
    text: "React, Typescript, ChartJS, Recharts, Tailwind",
  },
  {
    id: 10,
    link: "https://terjeee.github.io/2022-09-04-rest-countries-api/",
    linkRepo: "https://github.com/terjeee/2022-09-04-rest-countries-api",
    colorDot: "#F1E05A",
    title: "Countries API",
    text: "React, React Router, SCSS",
  },
  {
    id: 11,
    link: "https://svelte-sandbox-tau.vercel.app/",
    linkRepo: "https://github.com/terjeee/svelte-sandbox",
    colorDot: "#FF3E00",
    title: "Aftenposten",
    text: "Svelte, Typescript, D3, MapLibre, Tailwind",
  },
];
